package controller.event;

import java.util.EventObject;

import controller.component.PushButtonState;

/**
 * This event is generated by a hardware component such as a PushButton when the component-specific action occurs (such as being pressed).
 * @author sydxrey
 *
 */
public class PushButtonActionEvent extends EventObject {

	private static final long serialVersionUID = 1L;
	
	PushButtonState state;
	
	public PushButtonActionEvent(Object source, PushButtonState state) {
		super(source);
		this.state = state;
	}
	
	public PushButtonState getState() {
		return state;
	}
	
	@Override
	public String toString() {
		
		return super.toString() + ", state = " + state;
	}	
}
