package controller.event;

import java.util.EventObject;

/**
 * This event is generated by a hardware component such as a PushButton when the component-specific action occurs (such as being pressed).
 * @author sydxrey
 *
 */
public class PushButtonActionEvent extends EventObject {

	private static final long serialVersionUID = 1L;
	
	public PushButtonActionEvent(Object source) {
		super(source);
	}
	
	
}
